//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string BookName { get; set; }
        public int Cost { get; set; }
        public Nullable<int> NegotiatingCost { get; set; }
        public long id { get; set; }
        public int Owner_id { get; set; }
        public long Department_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User Owner { get; set; }
        public virtual User Negotiator { get; set; }
    }
}
